version: "3.9"
services:
  app:
    build:
      args:
        user: hop
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hopwebsite
    container_name: hopwebsite-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - hopwebsite

  # db:
  #   image: mysql:8.0
  #   container_name: hopwebsite-db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_USER: ${DB_USERNAME}
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - ./docker-compose/mysql:/docker-entrypoint-initdb.d
  #   networks:
  #     - hopwebsite

  nginx:
    image: nginx:alpine
    container_name: hopwebsite-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - hopwebsite

networks:
  hopwebsite:
    driver: bridge
